"""empty message

Revision ID: eb5eb88799ac
Revises: 38c4e85512a9
Create Date: 2022-03-23 17:39:53.712457

"""

# revision identifiers, used by Alembic.
revision = 'eb5eb88799ac'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
